### PR TITLE
theme packages: optional use of a separate definable source directory

### PR DESCRIPTION
**Pull request by SeifertDaniel**
allows a clearer structure within the theme packages

### CODE REVIEW

**Comment by Sieg** [comment]
Hi @SeifertDaniel, thanks for the pull request!

Could you please add a test for your case in ThemePackageInstallerTest? It will allow everyone to understand more clearly what structures you are trying to install.

Additionally, please, make sure you follow the PSR12, so Travis would be happy ;)

**Comment by Sieg** [comment]
Hello @SeifertDaniel, Any plans on finalizing this one?

**Comment by Sieg** [comment]
Hi @SeifertDaniel,

I have checked your suggested changes and added the test for the custom source case, but it might be not full.

**Please check pr22 branch.** - https://github.com/OXID-eSales/oxideshop_composer_plugin/compare/b-6.x...pr22

Still, I did not get what outcome we would like to achieve here:
- Are assets going to the custom_source as well or should they be separate? (probably not, as we have with modules)
- as i see EXTRA_PARAMETER_KEY_SOURCE is not used anywhere to compare or implement by already used standard.
- Assets directory modified, but assets are installed separately from the source, and the path will be incorrectly built in custom assets directory case at least, maybe in more situations as well.

As a result, i have removed assets directory modifications so custom source is appliable for source only, but not assets, as it uses different key, and probably by using that key, we can achieve custom assets to be in custom source as well, without a need to rely on custom source in path building.

I need you to:
* double-check the situation, describe how you feel it should work (regarding separate source and assets directories).
* add more tests to check if translations and any other special objects are installable where they should be.

**Comment by SeifertDaniel** [comment]
Hello Sieg,

Thank you very much for your effort.

Some time ago, we had learned in a telephone conversation with OXID that the definable source directories in the other package types (e.g. ModulePackageInstaller) is probably a legacy and is not desired there either. Rather, everything should be in the root folder and separated from the meta information by blacklist filters.

Before we (you and I) invest any more time here: What is your idea of the source directories?

Personally, I find the module package much clearer if all code and asset files are located separately. However, this is not my decision. Compare https://github.com/OXID-eSales/paypal and https://github.com/d3datadevelopment/Unzer as examples.

Best regards,
Daniel.

**Comment by Sieg** [comment]
Hi @SeifertDaniel, thanks a lot for checking this question again. I had another talk with Core as well. As you already mentioned - there are changes (and simplifications) in installation procedures of the modules already, And, improvements will come to theme installations as well, But, not right now. 

For now, we can still group a lot of things in the theme repositories together by directories and blacklist those development ones that we really don't want to be copied (as you already mentioned previously). And let's use the README.md files more widely - put more readable installation and development instructions in those, it's the best we can do to make development and installation processes easier and more smooth.

**Comment by Sieg** [comment]
Maybe one more small note - you gave the modules as example, but its a bit different there - We have a PHP code only in the source directory there, and registering a namespace for that directory; for the theme, we dont have php code with namespaces.

**Pull request closed without merging**
