### PR TITLE
Enable "discart-changes" (and more) in composer.json to update without asking

### PR DESCRIPTION
**Pull request by Sioweb**
Hi there,

EDIT: Here a little better explaining, why i would highly recommend this "feature" and pls sorry for my rude english - im not rude ^^ 

everytime i enter `composer update`, this plugin will ask me about 40 times if i rly want to overwrite code - if it has rly changed or not. I takes a lot of time if i want to update lokal more than some times a day, because i develop multiple modules/themes and libraries.

Next, automatic deployment via CI is still not possible. How should my CI accept all overwrites? Deleting all first? Remove the composer.lock file and enter `composer install` - to reinstall all the new Versions?

This PR adds the ability to skip all questions, like composer intendet it with "discard-changes".

```
{
  "config": {
    "discard-changes": true
  },
  "extra": {
    "discard-theme-changes": true,
    "discard-module-changes": true,
    "discard-shop-changes": true
  }
}
```

My Workflow is, developing all offline in Docker or Wampserver with .git directories in all my modules and themes. There i can commit changes directly to gitlab, which tag-pushes all changes to a private satis and packagist. I would prefer to not delete all directorie and files to skip overwrite questions, because i want to keep .qit directories - and it would wasting energy.

Well i think this PR could need two changes:

### "discard-changes": true

This is not needed with the other three changes, but makes all easier. But the other three options gives the ability to overwrite only _some_ files. Only some files are not okay for CI-Deployment. Or maybe its okay, because we build shop completly from Scratch an push it online (composer install) so we have nothing to overwrite.

### "extra"

All three options should be putten into a subarray like "oxidesales"

### Conclusion

I understand, that it could be better to accept every module, but with more than ten modules, every dev will just enter y y y y y y y... until its done. If he overwrite something, well, than he coded crappy and should learn how to use composer AND git ... no sorry for lazy coding from me :)

Next i think, it should be my decision if i take the risk to overwrite all.

What do u think?

### CODE REVIEW

**Comment by Sioweb** [comment]
We testet auto deploy with `composer install` to prevent this question, but oxid wont install Admin-Files with install. Only `composer update` install admin.

**Comment by leofonic** [comment]
Hello Sascha, some questions: 
Why "discard changes"? Discard changes sounds like changes should be reverted, but in fact the aim is to accept all changes, isn't it? 
Why not just change the default behaviour to "Y" instead of "N"?
Are you sure "install" doesn't install admin files? I use install and admin files are there.

**Comment by Sioweb** [comment]
Ho! leo,

well ney, `discard-changes` because "Änderungen verwerfen" and its what we want. Discard all changes and copy composed files there. And i think we should follow composer requirements: https://getcomposer.org/doc/06-config.md#discard-changes

Well if i think, that OXID ppl added this question, to prevent inadvertently loosing data, then it make sense to keep this question - like composer it want - and we better use a config or an extra option to controll this. Just for ppl who know what they do, or for autodeployment.

Yes, i got no admin files with composer install. Dont know why.

**Comment by leofonic** [comment]
OK i understand but the "discard-changes" in composer works differently, in case that there are no manual changes packages will be updated, regardless of the setting. 
When i suggest to change the default to "Y", the question would still be there, and could still be answered with "No" in case someone has changed a package in "source". But when using "no-interaction" or using the default, the shop would get updated correctly, which is not the case now. I think the default should work out-of-the-box, and only special cases should require user interaction or editing settings.

**Comment by Sioweb** [comment]
Yes, discard-changes need --no-interaction. Is okay for me to change `Y`to `N` then. Good point to prevent user from changing composer.json.

**Comment by Sieg** [comment]
Hello @Sioweb, is there any real use case for those "extra" config options? I am not sure if we really need it?

**Comment by Sioweb** [comment]
If i can remember right, this was to prevent the Question `Update operation will overwrite oxid-esales/paypal-module files. Do you want to continue? (y/N) `

The real usecase is to prevent this useless question, but as @leofonic wrote, better solution would be to add -n option, insteat of adding extra options to the root json.

But anyways, doesnt matter to me anymore, you can close this pr.

**Comment by Sieg** [comment]
We understand that it should be possible to run the update without overwriting questions (this part will be available soon), but, the question is - do we really need those EXTRA configurations to set answers by specific type? Can there be real case where it is needed?

**Comment by Sioweb** [comment]
I've just seen, that there three types of bundles.

Frontend-Dev will mostly work in themes, so he maybe wont update em, but modules doesnt matter to frontend-dev, so he could choose that composer update everything except themes - because he could loose his changes.

So ppl who work direktly in wave / flow / Theme-Without-Git, could skip the update. 

But now im not sure if anybody will use this feature.

**Comment by Sieg** [comment]
Hi @Sioweb, In the master of the shop, module files are no longer copied to the modules directory, and themes will be treated similarly soon. Thanks for triggering this discussion earlier.

**Pull request closed without merging**
